# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='myprofile',
            options={'verbose_name': '医生', 'verbose_name_plural': '医生管理'},
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='about_me',
            field=models.TextField(blank=True, verbose_name='关于我'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='出生日期'),
        ),
    ]
