# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20160705_1524'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='birth_date',
        ),
        migrations.AddField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(default=22, verbose_name='年龄'),
            preserve_default=False,
        ),
    ]
