# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-11 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20160711_2243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='age',
            field=models.IntegerField(null=True, verbose_name='年龄'),
        ),
    ]
