# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-08 07:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='content',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='news',
            name='tittle',
            field=models.CharField(max_length=200),
        ),
    ]
