# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 07:24
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_note',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2016, 7, 5, 7, 24, 45, 962294, tzinfo=utc), verbose_name='预约时间'),
            preserve_default=False,
        ),
    ]
