# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-07 15:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0002_register_note_register_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register_note',
            name='register_time',
        ),
        migrations.AddField(
            model_name='register_note',
            name='after_afternoon',
            field=models.BooleanField(default=False, verbose_name='上午还是下午'),
        ),
        migrations.AddField(
            model_name='register_note',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 7, 7, 15, 15, 41, 13541, tzinfo=utc), verbose_name='创建日期'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='register_note',
            name='paidui_number',
            field=models.IntegerField(default=1, verbose_name='队列号'),
            preserve_default=False,
        ),
    ]
