# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-06-15 06:36
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('hospital', '0002_auto_20160608_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, verbose_name='姓名')),
                ('workid', models.CharField(max_length=10, verbose_name='工号')),
                ('department', models.CharField(max_length=11, verbose_name='科室')),
                ('phonenumber', models.CharField(max_length=11, verbose_name='手机号')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '医生',
                'verbose_name_plural': '医生管理',
            },
        ),
    ]
