# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0004_auto_20160711_2243'),
    ]

    operations = [
        migrations.AddField(
            model_name='register_note',
            name='huizhen',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
