# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-12 07:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0005_register_note_huizhen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register_note',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.MyProfile'),
        ),
    ]
