# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0008_auto_20160712_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='content',
            field=models.CharField(default='adwdawdawdwad', max_length=3000, verbose_name='个人简历'),
            preserve_default=False,
        ),
    ]
