# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-13 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital', '0009_doctor_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='content',
            field=models.TextField(verbose_name='个人简历'),
        ),
    ]
